spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/bbdd-rck
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
